export ARCHFLAGS="-arch x86_64"
export PATH=/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:$PATH

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

[[ -f ~/.bashrc ]] && source ~/.bashrc
