- name: Ensure {{ name }} file exists
  copy:
    content: "{}"
    dest: "{{ path }}"
    force: no

- name: Load {{ name }} json
  include_vars:
    file: "{{ path }}"
    name: input_file

- name: Modify {{ name }} json
  set_fact:
    output_file: "{{ input_file | default([]) | combine(data) }}"

- name: Write {{ name }} json
  copy:
    content: "{{ output_file | to_nice_json }}"
    dest: "{{ path }}"
